# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

ports:
    resource:
        path: ../src/Weather/Domain/Port/
        namespace: App\Weather\Domain\Port
    type: attribute
