parameters:
    app.weather_cache_ttl: '%env(int:WEATHER_CACHE_TTL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            int $weatherCacheTtl: '%app.weather_cache_ttl%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Weather/Application/Contract/'

    App\Weather\Domain\WeatherSnapshotRepositoryInterface:
        alias: App\Weather\Infrastructure\Persistence\DoctrineWeatherSnapshotRepository

    App\Weather\Infrastructure\ThirdParty\WeatherProviderInterface:
        alias: App\Weather\Infrastructure\ThirdParty\OpenMeteoWeatherProvider

    App\Weather\Application\Query\ProviderWeatherQuery: ~

    App\Weather\Application\Query\LockedWeatherQuery:
        arguments:
            $inner: '@App\Weather\Application\Query\ProviderWeatherQuery'

    App\Weather\Application\Query\SnapshotWeatherQuery:
        arguments:
            $inner: '@App\Weather\Application\Query\LockedWeatherQuery'

    App\Weather\Application\Query\CachedWeatherQuery:
        arguments:
            $inner: '@App\Weather\Application\Query\SnapshotWeatherQuery'

    App\Weather\Application\Contract\WeatherQueryInterface:
        alias: App\Weather\Application\Query\CachedWeatherQuery
